### ISSUE TITLE
Macで実行したら動かなかった

### ISSUE THREAD

**Issue by Se1getsu** [gomazarashi/class_evaluation#2]
エラーが出た。
```
% pip install webdriver-manager
% py class_evaluation.py
入力された情報は授業評価アンケートの回答にのみ使用され、外部に送信されることはありません。

岡大IDを入力してください。
seig
パスワードを入力してください。(入力中のパスワードは表示されません)

学期を半角数字で入力してください。(例:1学期→1)
2
Traceback (most recent call last):
  File "/Users/kakky/.pyenv/versions/3.11.2/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kakky/.pyenv/versions/3.11.2/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 74, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kakky/Desktop/python/class_evaluation/class_evaluation.py", line 91, in <module>
    main()
  File "/Users/kakky/Desktop/python/class_evaluation/class_evaluation.py", line 77, in main
    driver = webdriver.Chrome(ChromeDriverManager().install())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kakky/.pyenv/versions/3.11.2/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 47, in __init__
    self.service.path = DriverFinder.get_path(self.service, self.options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kakky/.pyenv/versions/3.11.2/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 44, in get_path
    raise NoSuchDriverException(f"Unable to obtain {service.path} using Selenium Manager; {err}")
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; 'str' object has no attribute 'capabilities'; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

**Comment by gomazarashi** [comment]
古いバージョンのwebdriver-managerを使用していることによりエラーが発生していると考えられるため、バージョンを3.8.6から4.0.0に更新した後ファイルを再作成します。

**Comment by gomazarashi** [comment]
webdriver-managerの更新による正常な動作を確認したため、更新を反映したバージョンをv1.0.3としてリリースしました。

**Comment by Se1getsu** [comment]
プログラムがSeleniumの最新のバージョンに対応していないことが原因でした。
PR #3 で修正されました。
